apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chainDbOpenServer.name }}-service
  labels:
    {{- include "node-watcher.chainDbOpenServer.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.chainDbOpenServer.service.port }}
    protocol: TCP
  selector:
    {{- include "node-watcher.chainDbOpenServer.selectorLabels" . | nindent 4 }}
  type: ClusterIP
