apiVersion: v1
kind: Secret
metadata:
  name: prisma-config
  labels:
    {{- include "node-watcher.nodeWatcher.labels" . | nindent 4 }}
data:
  prisma-config: {{ include "node-watcher.prisma-config" . | b64enc }}
