apiVersion: v1
kind: Service
metadata:
  name: {{ include "polkassembly.authServer.fullname" . }}
  labels:
    {{- include "polkassembly.authServer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.authServer.service.type }}
  ports:
    - port: {{ .Values.authServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "polkassembly.authServer.matchLabels" . | nindent 4 }}
