apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "polkassembly.authServer.fullname" . }}
  labels:
    {{- include "polkassembly.authServer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.authServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "polkassembly.authServer.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "polkassembly.authServer.matchLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml ".Values.authServer.podSecurityContext" | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml ".Values.authServer.securityContext" | nindent 12 }}
          image: "{{ .Values.authServer.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.authServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml ".Values.authServer.resources" | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.authServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.authServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
