apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chainDbWatcher.name }}-service
  labels:
    {{- include "polkassembly.chainDbWatcher.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.chainDbWatcher.config.HEALTH_PORT }}
      protocol: TCP
  selector:
    {{- include "polkassembly.chainDbWatcher.selectorLabels" . | nindent 4 }}
