apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.chainDbWatcher.name }}-config
  labels:
    {{- include "polkassembly.chainDbWatcher.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.chainDbWatcher.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
