apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  labels:
    {{- include "polkassembly.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "polkassembly.frontend.selectorLabels" . | nindent 4 }}
