apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hasura.name }}-service
  labels:
    {{- include "polkassembly.hasura.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hasura.service.type }}
  ports:
    - port: {{ .Values.hasura.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "polkassembly.hasura.selectorLabels" . | nindent 4 }}
