apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hasura.name }}
  labels:
    {{- include "polkassembly.hasura.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.hasura.replicaCount }}
  selector:
    matchLabels:
      {{- include "polkassembly.hasura.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "polkassembly.hasura.matchLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.hasura.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.hasura.securityContext | nindent 12 }}
          image: "{{ .Values.hasura.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.hasura.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.hasura.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.hasura.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.hasura.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
