apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hasura.name }}-config
  labels:
    {{- include "polkassembly.hasura.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.hasura.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- with .Values.nodeSelector }}
nodeSelector:
{{ toYaml . | indent 2 }}
{{- end }}
