apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.healthMonitor.name }}-config
  labels:
    {{- include "polkassembly.healthMonitor.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.healthMonitor.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
