stages:
  - test
  - build

cache:
  key: '${CI_JOB_NAME}'
  paths:
    - node_modules/
    - packages/*/node_modules/

lint-front-end:
  stage: test
  image: node:12
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - cd front-end
    - yarn install
    - yarn lint
  rules:
    - changes:
      - "front-end/*"
  tags:
    - linux-docker
lint-back-end:
  stage: test
  image: node:12
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH
    - cd auth-server
    - yarn install
    - yarn lint
  rules:
    - changes:
      - "auth-server/*"
  tags:
    - linux-docker