version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    ports:
    - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: governance-auth
      PGDATA: /var/lib/postgresql/data
    volumes:
    # persistent data locally
    - ./data:/var/lib/postgresql/data
