version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - target: 5433
        published: 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPORT: 5433
      POSTGRES_DB: governance-auth-test
    container_name: governance-auth-test
  auth-test:
    image: paritytech/polkassembly-auth-test
    depends_on:
      - "postgres"
    environment:
      NODE_ENV: test
      TEST_DATABASE_URL: "postgres://postgres:postgres@postgres:5433/governance-auth-test"
      SENDGRID_API_KEY: ""
