apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: front-end
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: gcr.io/test-installations-222013/polkassembly-front-end:master
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: config
          subPath: default.conf
      volumes:
      - name: config
        configMap:
          name: front-end-nginx-config
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
