apiVersion: v1
kind: Secret
metadata:
  name: graphql-jwt-secret
  namespace: polkassembly
type: Opaque
data:
  graphql-jwt-secret: eyAidHlwZSI6ICJSUzI1NiIsICJrZXkiOiAiLS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2WG4xZnpCQkFZTmZJZFBvUlplcgowNFhObjQyUXBWWUJlU3Njc1FsSFNhaHFuUWNlNEJxUHFLRDdNS01CeTBBdy9FUWlvK2VpUWtEMm5XaGkwZGFLCjJ1SjdiUW5BYUFuMTQ0dkZRRUlGRnpLeFIxMFdsaUpjZUVwb0w1SW9BMlg2amRoRjVmdkNxQUxVUmc1aTRZOUEKYVJxdW9VU2tvMHBJa1NIaGYyRGJEY0FDVm9TREdNbGtHQVU5YlJYa3daM0xwcW90NnIyOGc5VS9UOTI5elZwdQorVDAweXlJY3RUNUpKYWxiRDBZVG5Va09MYTJXQnhtbXFJRXUzeFBJVng5YTh6RzFLL294ZGpTMHJvR2M4QWkrCmlDV3A3V3FXazg4ZklOaXRONnY3TWZwNCtJVEN3RVhITEg0OFFqLytZWFRGUFFTZzZsVm1tclBmWDYxRjZyR1gKd1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tIiB9
