# Default values for polkassembly.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: regcred
nodeSelector: {}
cloudsqlInstanceCredentials: some-secret.json-from-gitlab-vars

frontend:
  name: frontend
  replicaCount: 1

  image:
    repository: gcr.io/test-installations-222013
    pullPolicy: Always

  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.frontend.entryPoints: "https,http"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []

  resources: {}
  tolerations: []
  affinity: {}

hasura:
  name: hasura
  replicaCount: 1

  config:
    hasuraGraphqlAdminSecret: "from-gitlab-vars"
    hasuraGraphqlDatabaseUrl: "from-gitlab-vars"
    hasuraGraphqlEnabLeConsole: "true"
    hasuraGraphqlEnabledLogTypes: "startup, http-log, webhook-log, websocket-log, query-log"
    hasuraGraphqlUnauthorizedRole: anonymous
    hasuraPostSubscriptionHook: http://auth-server-service:8010/auth/graphql
    hasuraPostSubscriptionSecret: "from-gitlab-vars"
    hasuraCommentCreateEventHook: http://auth-server-service:8010/auth/event/comment/create
    hasuraOnchainLinkCreateHook: http://auth-server-service:8010/auth/event/onchain_link/create
    hasuraEventSecret: "from-gitlab-vars"
    hasuraAuthServerRemoteSchema: http://auth-server-service:8010/auth/graphql
    hasuraChainDbRemoteSchema: "from-gitlab-vars"

  image:
    repository: nginx
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 80

  resources: {}
  tolerations: []
  affinity: {}

authServer:
  name: authServer
  replicaCount: 1

  config:
    proposalBotUserId: from-gtilab-vars
    databaseUrl: from-giltab-vars
    domainName: "test.polkassembly.io"
    hasuraPostSubscriptionSecret: from-gitlab-vars
    hasuraEventSecret: from-gitlab-vars
    jwtKeyPassphrase: from-gitlab-vars
    nodeEnv: "development"
    port: 8010
    sendgridApiKey: from-gitlab-vars

  image:
    repository: nginx
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    port: 80

  resources: {}
  tolerations: []
  affinity: {}

chainDbWatcher:
  name: chainDbWatcher
  replicaCount: 1

  image:
    repository: nginx
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  podSecurityContext: {}
  securityContext: {}

  resources: {}
  tolerations: []
  affinity: {}
