name: Front-end lint

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - 'front-end/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: cd front-end && yarn install && yarn lint
